# ä¸»é¢˜åŸºæœ¬ä¿¡æ¯
# theme basic info
theme_info:
  name: ILS
  version: 1.1.1
  author: XPoet
  repository: https://github.com/XPoet/hexo-theme-ils

# ç½‘ç«™å›¾æ ‡
# favicon
favicon: images/favicon.png

# å¤´åƒ
# avatar
avatar: images/avatar.png

# å¯¼èˆªèœå•
# navigation menu
menu:
  Home: /
  Archives: /archives
  Links: /links
  About: /about
  # ...

# RSS è®¢é˜…
# RSS
rss:
  enable: true

# è¯„è®ºæ’ä»¶
# comment plugin
comments:
  # Valine https://github.com/xCss/Valine
  valine:
    enable: true
    appid: ih2nzG3ilVNdLgJK4kBXTjOq-gzGzoHsz
    appkey: gdf6tXXLBTLg9qpjS2y6Tbw7
    # meta: ['nick', 'mail']
    meta: ['nick', 'mail', 'link']
    placeholder: ğŸ˜œå°½æƒ…åæ§½å§~

  # Gitalk https://github.com/gitalk/gitalk
  gitalk:
    enable: false
    github_id: XPoet
    repository: gitalk-comments-data
    client_id: e7f9c899d3766b200da8
    client_secret: 77fa7aa00f20f512ac14e6599f8b433e9fe2f4d5

# ç½‘ç«™è®¡æ•°
# website count
website_count:
  # busuanzi http://ibruce.info/2015/04/04/busuanzi/
  busuanzi_count:
    enable: true
    site_uv: false
    site_pv: true
    page_pv: true

# æœ¬åœ°æœç´¢
# ä¾èµ–ï¼šhexo-generator-searchdb https://github.com/theme-next/hexo-generator-searchdb
# Local Search
# Dependencies: hexo-generator-searchdb https://github.com/theme-next/hexo-generator-searchdb
local_search:
  enable: true

  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto  # values: auto | manual

  # Unescape html strings to the readable one.
  unescape: false

  # Preload the search data when the page loads.
  preload: true

# ä»£ç å¤åˆ¶
# Code Copy
code_copy:
  enable: true
  style: flat  # values: default | flat | mac

# ä¾§è¾¹æ å·¥å…·
# sidebar tools
side_tools:
  enable: true
  position: right  # values: left | right

# å›åˆ°é¡¶éƒ¨
# back to top
back2top:
  enable: true
  position: right  # values: left | right

# ç›®å½•ç»“æ„
# Table of Contents in the Sidebar
toc:
  enable: true

  # Automatically add list number to toc.
  number: true

  # If true, all level of TOC in a post will be displayed, rather than the activated part of it.
  expand_all: true

# magic ä¸»é¢˜
# magic theme
magic:
  enable: true
  transform: true
  sidebar:
    enable: false
    fixed: true
    position: right  # values: left | right
